<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    Acc <?= $AccId ?> created successfully. <br>
    <!DOCTYPE html>
    <body>
<form>
    <table border=""0>
        <tr>
            <td>Account Number:</td>
            <td align = "center"><input type="text" name="acc_cus" size="30" /></td>
        </tr>
        <tr>
            <td>Account Balance:</td>
            <td align = "center"><input type="text" name="acc_balance" size="30" /></td>
        </tr>
        <tr>
            <td colspan="2" align="center" ><input type="submit" value="Submit" /> </td>
        </tr>


    </table>
</form>
    <a href=<?= $linkTo('accIndex'); ?>>Back</a>
    <br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>