<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<h1>Welcome to ..prepepep.</h1>
The accounts are:
<table>
    <?php foreach ($accounts as $account) { ?>
    <tr>
        <td><?= $account->getId() ?></td>
        <td><?= $account->getName() ?></td>
        <td><a href= <?= $linkTo('accountDelete', ['id' => $account->getId()]);?> >delete</a></td>
    </tr>
    <?php } ?>
</table>

    <a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
    <a href=<?= $linkTo('customerCreate'); ?>>Create new customer.</a>
    <a href=<?= $linkTo('loginCreate'); ?>>Create new login.</a>
    <a href=<?= $linkTo('customer_accCreate'); ?>>Create new transaction.</a>
    <a href=<?= $linkTo('accCreate'); ?>>My New Account
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>