<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <h1>Welcome to Massey Bank.</h1>
    The accounts are:
    <table>
        <?php foreach ($logins as $login) { ?>
            <tr>
                <td><?= $login->getLogin_acc() ?></td>
                <td><?= $login->getLogin_user() ?></td>
                <td><?= $login->getLogin_pword() ?></td>
                <td><a href= <?= $linkTo('loginDelete', ['id' => $login->getLogin_acc()]);?> >delete</a></td>
            </tr>
        <?php } ?>
    </table>

    <a href=<?= $linkTo('loginCreate'); ?>>Create new log in.</a>
    <a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
    <a href=<?= $linkTo('customerCreate'); ?>>Create new customer.</a>
    <a href=<?= $linkTo('customer_accCreate'); ?>>Create new Transaction.</a>
    <br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>